# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dumps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dumps.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.OneToOneField(max_length=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDump',
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dumps.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='dumps.Membership', to='dumps.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.OneToOneField(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
