# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dumps', '0003_auto_20161027_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('download_date', models.DateTimeField(default=datetime.datetime(2016, 11, 1, 23, 40, 58, 595932))),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dumps.Person')),
            ],
        ),
    ]
