# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumps', '0004_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='download_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
